import React from "react";
import ClausePartsPage from "./ClausePartsPage";

export default {
  title: "pages/clause/ClausePartsPage",
  component: ClausePartsPage,
};

const defaultProps = {
  clauseNumber: 282,
  year: 2019,
  view: "page" as const,
  parts: [
    {
      part: "282ч1",
      name: "Описание части",
      totalConvicted: 900,
      totalAcquittal: 40,
      totalDismissal: 300,
      coerciveMeasures: 300,
      unfinishedOffence: 300,
      addTotalPersons: 300,
      addTotalOffences: 300,
      addAcquittalPersons: 300,
      addAcquittalOffences: 300,
      noCrimeSelfDefence: 300,
      noCrimeNecessity: 300,
      noCrimeOther: 300,
      primaryLifeSentence: 300,
      primarySuspended: 300,
      primaryArrest: 300,
      primaryRestrain: 300,
      primaryRestrain2009: 300,
      primaryCorrectionalLabour: 300,
      primaryCommunityService: 300,
      primaryForcedLabour: 300,
      primaryFine: 300,
      primaryDisqualification: 300,
      primaryOther: 300,
      primaryMilitaryDisciplinaryUnit: 300,
      primaryRestrictionsInMilitaryService: 300,
      primaryImprisonment: 300,
      addDisqualification: 300,
      addFine: 300,
      addTitlesWithdraw: 300,
      addRestrain: 300,
      dismissalAbsenceOfEvent: 300,
      dismissalAmnesty: 300,
      dismissalReconciliation: 300,
      dismissalRepentance: 300,
      dismissalCourtFine: 300,
      dismissalOther: 300,
      dismissalRepentance2: 300,
      addDismissalPersons: 300,
      addDismissalOffences: 300,
      addDismissalOtherPersons: 300,
      addDismissalOtherOffences: 300,
    },
    {
      part: "282ч2",
      name: "Описание части",
      totalConvicted: 101,
      totalAcquittal: 40,
      totalDismissal: 300,
      coerciveMeasures: 300,
      unfinishedOffence: 300,
      addTotalPersons: 300,
      addTotalOffences: 300,
      addAcquittalPersons: 300,
      addAcquittalOffences: 300,
      noCrimeSelfDefence: 300,
      noCrimeNecessity: 300,
      noCrimeOther: 300,
      primaryLifeSentence: 300,
      primarySuspended: 300,
      primaryArrest: 300,
      primaryRestrain: 300,
      primaryRestrain2009: 300,
      primaryCorrectionalLabour: 300,
      primaryCommunityService: 300,
      primaryForcedLabour: 300,
      primaryFine: 300,
      primaryDisqualification: 300,
      primaryOther: 300,
      primaryMilitaryDisciplinaryUnit: 300,
      primaryRestrictionsInMilitaryService: 300,
      primaryImprisonment: 300,
      addDisqualification: 300,
      addFine: 300,
      addTitlesWithdraw: 300,
      addRestrain: 300,
      dismissalAbsenceOfEvent: 300,
      dismissalAmnesty: 300,
      dismissalReconciliation: 300,
      dismissalRepentance: 300,
      dismissalCourtFine: 300,
      dismissalOther: 300,
      dismissalRepentance2: 300,
      addDismissalPersons: 300,
      addDismissalOffences: 300,
      addDismissalOtherPersons: 300,
      addDismissalOtherOffences: 300,
    },
  ],
};

export const withGraphs = (): React.ReactNode => (
  <ClausePartsPage {...defaultProps} />
);

export const withTable = (): React.ReactNode => (
  <ClausePartsPage {...defaultProps} view="table" />
);
