import React from "react";
import Header from "src/components/Header";
import Footer from "src/components/Footer";
import { TargemProvider } from "react-targem";
import "src/styles/global.css";

// translation.json file is autogenerated and ignored
// so we use require() to prevent tsc compile time errors before webpack is first run
// eslint-disable-next-line @typescript-eslint/no-var-requires
const translationsJson = require("src/i18n/translations.json");

interface Props {
  children?: React.ReactNode;
  hasPageLayout?: boolean;
}

const Layout: React.FC<Props> = ({ children, hasPageLayout = true }: Props) => {
  return (
    <TargemProvider detectLocale translations={translationsJson}>
      {hasPageLayout ? <Header /> : null}
      {children}
      {hasPageLayout ? <Footer /> : null}
    </TargemProvider>
  );
};

export default Layout;
