import React, { useEffect } from "react";
// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
import emergence from "emergence.js";

import Navibar from "src/components/navibar";
import Footer from "src/components/footer";
import { siteMetadata } from "../../../gatsby-config";

import "modern-normalize/modern-normalize.css";
import "prismjs/themes/prism.css";
import "src/scss/gatstrap.scss";
import "animate.css/animate.css";
import "font-awesome/css/font-awesome.css";
import { TargemProvider } from "react-targem";

// translation.json file is autogenerated and ignored
// so we use require() to prevent tsc compile time errors before webpack is first run
// eslint-disable-next-line @typescript-eslint/no-var-requires
const translationsJson = require("src/i18n/translations.json");

interface Props {
  children?: React.ReactNode;
  location: Location;
}

const Layout: React.FC<Props> = ({ children, location }: Props) => {
  useEffect(() => {
    emergence.init();
  });

  return (
    <TargemProvider detectLocale translations={translationsJson}>
      <Navibar title={siteMetadata.title} location={location} />
      {children}
      <Footer title={siteMetadata.title} />
    </TargemProvider>
  );
};

export default Layout;
