import React from "react";
import Navibar from "src/components/Navibar";
import Footer from "src/components/Footer";
import { siteMetadata } from "../../../gatsby-config";
import { TargemProvider } from "react-targem";
import "src/styles/global.css";

// translation.json file is autogenerated and ignored
// so we use require() to prevent tsc compile time errors before webpack is first run
// eslint-disable-next-line @typescript-eslint/no-var-requires
const translationsJson = require("src/i18n/translations.json");

interface Props {
  children?: React.ReactNode;
}

const Layout: React.FC<Props> = ({ children }: Props) => {
  return (
    <TargemProvider detectLocale translations={translationsJson}>
      <Navibar />
      {children}
      <Footer title={siteMetadata.title} />
    </TargemProvider>
  );
};

export default Layout;
